version: "3"

services:
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fluxo-de-caixa-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fluxo-de-caixa-sql-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"

  mongo-db:
    image: mongo
    container_name: fluxo-de-caixa-mongo-db
    ports:
      - "27017:27017"    

  api-caixa:
    image: "raftriani/fluxo-de-caixa-api-caixa:latest"
    container_name: "fluxo-de-caixa-api-caixa"
    build:
      context: "../"
      dockerfile: "./src/FluxoDeCaixa.Lancamentos.API/Dockerfile"
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5000

  api-relatorios:
    image: "raftriani/fluxo-de-caixa-api-relatorios:latest"
    container_name: "fluxo-de-caixa-api-relatorios"
    build:
      context: "../"
      dockerfile: "./src/FluxoDeCaixa.Relatorios.API/Dockerfile"
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5002
